<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Diseño de experimentos – Análisis de Datos en Agricultura con R y RStudio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./06-regresion.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-874a94cc35be0778ec714a6aca2fed85.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sín resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la busqueda",
    "search-hide-matches-text": "Esconder resultados adicionales",
    "search-more-match-text": "hay más resultados en este documento",
    "search-more-matches-text": "más resultados en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script type="module" src="site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
<link href="site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-DOE.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Diseño de experimentos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de Datos en Agricultura con R y RStudio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A modo de introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R y RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estadística. Conceptos Básicos.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-estdesc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estadística Descriptiva</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distribuciones de probabilidad</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Muestreo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-icph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estadística Inferencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-regresion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Correlación y Regresión</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-DOE.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Diseño de experimentos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="-1">
    <h2 id="toc-title">Indice de contenidos</h2>
   
  <ul>
  <li><a href="#conceptos-básicos" id="toc-conceptos-básicos" class="nav-link active" data-scroll-target="#conceptos-básicos"><span class="header-section-number">8.1</span> Conceptos básicos</a></li>
  <li><a href="#principios-básicos" id="toc-principios-básicos" class="nav-link" data-scroll-target="#principios-básicos"><span class="header-section-number">8.2</span> Principios básicos</a></li>
  <li><a href="#análisis-de-varianza-anova-andeva" id="toc-análisis-de-varianza-anova-andeva" class="nav-link" data-scroll-target="#análisis-de-varianza-anova-andeva"><span class="header-section-number">8.3</span> Análisis de Varianza (ANOVA, ANDEVA)</a>
  <ul>
  <li><a href="#modelos-para-el-análisis-de-varianza" id="toc-modelos-para-el-análisis-de-varianza" class="nav-link" data-scroll-target="#modelos-para-el-análisis-de-varianza"><span class="header-section-number">8.3.1</span> Modelos para el análisis de varianza</a></li>
  <li><a href="#tabla-anova" id="toc-tabla-anova" class="nav-link" data-scroll-target="#tabla-anova"><span class="header-section-number">8.3.2</span> Tabla ANOVA</a></li>
  </ul></li>
  <li><a href="#diseño-completo-al-azar" id="toc-diseño-completo-al-azar" class="nav-link" data-scroll-target="#diseño-completo-al-azar"><span class="header-section-number">8.4</span> Diseño completo al azar</a></li>
  <li><a href="#pruebas-de-comparaciones-múltiples-para-la-media." id="toc-pruebas-de-comparaciones-múltiples-para-la-media." class="nav-link" data-scroll-target="#pruebas-de-comparaciones-múltiples-para-la-media."><span class="header-section-number">8.5</span> Pruebas de comparaciones múltiples para la media.</a>
  <ul>
  <li><a href="#contrastes-a-priori" id="toc-contrastes-a-priori" class="nav-link" data-scroll-target="#contrastes-a-priori"><span class="header-section-number">8.5.1</span> Contrastes <em>a priori</em></a>
  <ul class="collapse">
  <li><a href="#contrastes-ortogonales" id="toc-contrastes-ortogonales" class="nav-link" data-scroll-target="#contrastes-ortogonales"><span class="header-section-number">8.5.1.1</span> Contrastes ortogonales</a></li>
  <li><a href="#contrastes-polinomiales" id="toc-contrastes-polinomiales" class="nav-link" data-scroll-target="#contrastes-polinomiales"><span class="header-section-number">8.5.1.2</span> Contrastes polinomiales</a></li>
  </ul></li>
  <li><a href="#contrastes-a-posteriori" id="toc-contrastes-a-posteriori" class="nav-link" data-scroll-target="#contrastes-a-posteriori"><span class="header-section-number">8.5.2</span> Contrastes <em>a posteriori</em></a>
  <ul class="collapse">
  <li><a href="#clasificación-de-pruebas-de-comparación-múltiple-de-medias" id="toc-clasificación-de-pruebas-de-comparación-múltiple-de-medias" class="nav-link" data-scroll-target="#clasificación-de-pruebas-de-comparación-múltiple-de-medias"><span class="header-section-number">8.5.2.1</span> Clasificación de Pruebas de Comparación Múltiple de Medias</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#diseño-de-bloques-completos-al-azar" id="toc-diseño-de-bloques-completos-al-azar" class="nav-link" data-scroll-target="#diseño-de-bloques-completos-al-azar"><span class="header-section-number">8.6</span> Diseño de bloques completos al azar</a></li>
  <li><a href="#diseño-de-cuadro-latino" id="toc-diseño-de-cuadro-latino" class="nav-link" data-scroll-target="#diseño-de-cuadro-latino"><span class="header-section-number">8.7</span> Diseño de cuadro latino</a></li>
  <li><a href="#pruebas-no-paramétricas-equivalentes-al-análisis-de-varianza" id="toc-pruebas-no-paramétricas-equivalentes-al-análisis-de-varianza" class="nav-link" data-scroll-target="#pruebas-no-paramétricas-equivalentes-al-análisis-de-varianza"><span class="header-section-number">8.8</span> Pruebas no paramétricas equivalentes al análisis de varianza</a></li>
  <li><a href="#pruebas-de-comparaciones-múltiples-no-paramétricas" id="toc-pruebas-de-comparaciones-múltiples-no-paramétricas" class="nav-link" data-scroll-target="#pruebas-de-comparaciones-múltiples-no-paramétricas"><span class="header-section-number">8.9</span> Pruebas de comparaciones múltiples no paramétricas</a></li>
  <li><a href="#diseño-factorial" id="toc-diseño-factorial" class="nav-link" data-scroll-target="#diseño-factorial"><span class="header-section-number">8.10</span> Diseño factorial</a></li>
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios">Ejercicios</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="doe" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Diseño de experimentos</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El diseño de experimentos fue inventado por Ronald A. Fisher en las décadas de 1920 y 1930 en la Estación Experimental de Rothamsted, conocida ahora como Rothamsted Research. En el primer libro de Fisher sobre diseño de experimentos mostró cómo se podían extraer conclusiones válidas a partir de experimentos con fluctuaciones naturales como la temperatura, las condiciones del suelo y la lluvia, es decir, en presencia de variables molestas o perturbadoras.</p>
<p>Las variables perturbadoras conocidas suelen causar sesgos sistemáticos en grupos de resultados (por ejemplo, variación entre lotes). Las variables perturbadoras desconocidas suelen causar variabilidad aleatoria en los resultados y se denominan variabilidad inherente o ruido. Aunque el método de diseño experimental se utilizó por primera vez en un contexto agrícola, el método se ha aplicado con éxito en otras industrias y ámbitos.</p>
<p>En la <a href="01-concepts.html#sec-tipest" class="quarto-xref"><span>Sección 2.6</span></a> se presentaron los tipos de estudio, en esta sección se presentan los principios básicos y los principales diseños experimentales usados en agricultura. ¿Por qué es importante el diseño experimental? Supongamos que deseamos comparar dos variedades de maíz, una variedad estándar ya conocida a la que llamaremos V1 y una variadad nueva de la que recién hemos escuchado a la que llamaremos V2. Podríamos plantar la mitad de un campo con V1 y la otra mitad con V2. Se plantan las dos variedades exactamente el mismo día y se gestionan las dos mitades del campo exactamente igual durante todo el período vegetativo. A lo largo de la cosecha, se llevan registros separados del rendimiento de cada mitad del campo, de modo que al final de la temporada se obtiene el rendimiento total de cada variedad. Supongamos que, en este caso, la nueva variedad (V2) tiene un rendimiento un 20% mayor que la variedad estándar (V1). ¿Puede asegurar que la nueva variedad es mejor que la variedad estándar? La respuesta es no, porque puede haber otros factores que hayan provocado la diferencia de rendimiento, como por ejemplo:</p>
<ul>
<li>V2 se plantó en una parte del campo que tenía mejor suelo.</li>
<li>Un extremo del campo era más húmedo que el otro y algunos de las plantes se infectaron con oídio.</li>
<li>Las diferencias de textura del suelo provocaron un aumento de la humedad del suelo de un extremo del campo al otro.</li>
<li>Una parte del campo con la variedad estándar recibe sombra por la tarde de una línea de árboles adyacente.</li>
<li>La presencia de malezas es mayor en una parte del campo con V1.</li>
<li>Los bosques o zonas silvestres adyacentes son una fuente de plagas que afectan más a un extremo del campo que al otro.</li>
</ul>
<p>Como el experimento no se preparó para tener en cuenta la variabilidad del campo, no se puede concluir si el rendimiento superior de una variedad se debió a la propia variedad o a diferencias en las condiciones de cultivo. No se repitieron los tratamientos. Por lo tanto, no tiene forma de aplicar una prueba estadística a sus datos. Si piensa en su propia explotación, ¿qué otras fuentes de variación podrían influir en su pregunta de investigación?</p>
<p>Con el diseño experimental y el análisis estadístico adecuados, puede identificar y aislar los efectos de la variación natural y determinar si las diferencias entre tratamientos son «reales», dentro de ciertos niveles de probabilidad. La elección del diseño experimental, dependerá en gran medida de la pregunta de investigación que se plantee y del número de tratamientos del experimento.</p>
<section id="conceptos-básicos" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="conceptos-básicos"><span class="header-section-number">8.1</span> Conceptos básicos</h2>
<ol type="1">
<li><strong>Unidad experimental</strong>: el objeto o espacio al cual se aplica el tratamiento y donde se analiza la variable o variables investigadas. Dependiendo del tipo de experimento la unidad experimental puede ser un animal, un árbol o una parcela. Cuando la unidad experimental es una parcela, en algunas ocsiones se presenta el efecto borde.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Efecto borde
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las diferencias que se observan en el crecimiento y producción de plantas que se ubican en los perímetros de una parcela comparadas con las que se ubican en la zona central de la parcela se conocen como efecto borde, este efecto puede ser causado por:</p>
<ul>
<li>Vecindad de las parcelas o áreas no cultivadas lo que puede producir que las plantas del perímetro tengan menor competencia de luz y nutrientes.</li>
<li>Competencia entre los tratamientos.</li>
</ul>
</div>
</div>
<ol start="2" type="1">
<li><p><strong>Tratamiento</strong>: el tratamiento es el procedimiento cuyo efecto se mide y que se desea comparar con otros tratamientos. Ejemplos de tratamiento pueden ser la ración alimenticia, una variedad de semillas, un programa de riego, la concentración de un herbicida o fungicida, una combinación de temperatura y humedad.</p></li>
<li><p><strong>Unidad de muestreo</strong>: el efecto del tratamiento se puede medir en una fracción de la unidad experimental o en toda la unidad experimental. Es decir que la unidad de muestreo puede ser toda la unidad experimental o una fracción de la misma. Ejemplos de unidad de muestreo son: un animal sometido a una ración de alimento, muestra aleatoria de las hojas de una planta, la cosecha de 10 plantas de la unidad experimental en una parcela.</p></li>
<li><p><strong>Error experimental</strong>: Medida de la variación existente entre las observaciones realizadas en las unidades experimentales tratadas en forma similar. La variación puede provenir de dos fuentes:</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Fuentes de la variación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Variabilidad propia del material experimental al que se aplican los tratamientos.</li>
<li>Variación resultado de cualquier falta de uniformidad en la realización física del experimento.</li>
</ul>
</div>
</div>
<ol start="5" type="1">
<li><strong>Repeticiones</strong>: número de veces que un tratamiento aparece en un experimento.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Funciones de las repeticiones
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Permitir una estimación del error experimental.</li>
<li>Mejorar la precisión de un experimento mediante la reducción del error estándar de una media de tratamiento.</li>
<li>Aumentar el alcance de la inferencia del experimento mediante la selección y el uso adecuado de unidades experimentales más variables.</li>
<li>Controlar la varianza del error.</li>
</ul>
</div>
</div>
<p>Aumentar el número de repeticiones, la mayoría de las veces, mejora la precisión. La elección del número de repeticiones de un experimento depende de varios factores, como el nivel de confianza deseado, la variabilidad esperada de los datos, el tamaño del efecto que se desea detectar, la disponibilidad de recursos y la complejidad del experimento; por lo general, un buen punto de partida es intentar realizar al menos tres repeticiones por condición, pero es posible que se necesiten más dependiendo de la pregunta de investigación específica y del diseño experimental.</p>
</section>
<section id="principios-básicos" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="principios-básicos"><span class="header-section-number">8.2</span> Principios básicos</h2>
<p>En el diseño de experimentos, el <strong>control del error experimental</strong> se refiere a la minimización de la variabilidad de los resultados que no está directamente relacionada con los factores estudiados, lo que se consigue mediante los principios como la aleatorización, la replicación y el bloqueo (control local), cuyo objetivo es aislar el verdadero efecto de las variables manipuladas y reducir la influencia de factores ajenos al resultado.</p>
<ol type="1">
<li><strong>Aleatorización</strong>: La asignación aleatoria de los tratamientos a las unidades experimentales ayuda a distribuir por igual cualquier fuente desconocida de variación entre los grupos de tratamiento, reduciendo el sesgo.</li>
<li><strong>Repetición</strong>: La repetición de cada condición de tratamiento varias veces en diferentes unidades experimentales permite estimar el error experimental y aumenta la precisión de los resultados.</li>
<li><strong>Bloqueo (control local)</strong>: Agrupar unidades experimentales similares en bloques y asignar tratamientos dentro de cada bloque ayuda a controlar las fuentes conocidas de variación que podrían afectar a los resultados, como las diferencias en las condiciones ambientales.</li>
</ol>
</section>
<section id="análisis-de-varianza-anova-andeva" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="análisis-de-varianza-anova-andeva"><span class="header-section-number">8.3</span> Análisis de Varianza (ANOVA, ANDEVA)</h2>
<p>El <strong>An</strong>álisis <strong>De</strong> <strong>Va</strong>rianza o prueba ANOVA (abreviatura de <strong>An</strong>alysis <strong>o</strong>f <strong>Va</strong>riance) es una técnica que se utiliza para comparar las medias de más de dos grupos. Las comparaciones se hacen analizando la <strong>variabilidad</strong> dentro y entre los grupos. Como toda prueba de hipótesis tiene una hipótesis nula (<span class="math inline">\(H_0\)</span>), en este caso, para los <span class="math inline">\(k\)</span> grupos o poblaciones la hipótesis nula es que las medias de todos los grupos o poblaciones son iguales; mientras que la hipótesis alternativa es que al menos una de las medias es diferente:</p>
<p><span class="math display">\[
\begin{cases}
H_0: \mu_1 = \mu_2 = \ldots = \mu_k \\
H_1: \exists \; i, \; j \; \text{tal que} \; \mu_i \neq \mu_j
\end{cases}
\]</span></p>
<section id="modelos-para-el-análisis-de-varianza" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="modelos-para-el-análisis-de-varianza"><span class="header-section-number">8.3.1</span> Modelos para el análisis de varianza</h3>
<p>Vamos a suponer que deseamos comparar <span class="math inline">\(k\)</span> tratamientos o niveles para un <span class="math inline">\(único factor\)</span>, cada tratamiento o nivel tiene <span class="math inline">\(r\)</span> repeticiones. La respuesta observada es una variable aleatoria. Los datos del modelo se pueden presentar de la siguiente forma:</p>
<div id="tbl-datosanova" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-datosanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.1: Datos de un experimento de un factor único
</figcaption>
<div aria-describedby="tbl-datosanova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Trat.-Nivel</th>
<th style="text-align: right;">Repetición 1</th>
<th style="text-align: right;">Repetición 2</th>
<th style="text-align: right;"><span class="math inline">\(\ldots\)</span></th>
<th style="text-align: right;">Repetición <span class="math inline">\(r\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;"><span class="math inline">\(y_{11}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{12}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{1r}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;"><span class="math inline">\(y_{21}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{22}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{2r}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(k\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{k1}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{k2}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: right;"><span class="math inline">\(y_{kr}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El modelo matemático correspondiente puede ser escrito como:</p>
<p><span id="eq-modmed"><span class="math display">\[
y_{ij} = \mu_i + \epsilon_{ij} \quad \forall \; i,j
\tag{8.1}\]</span></span></p>
<p>donde <span class="math inline">\(y_{ij}\)</span> corresponde a la <span class="math inline">\(j-ésima\)</span> repetición para el <span class="math inline">\(i-ésimo\)</span> nivel o tratamiento, <span class="math inline">\(\mu_i\)</span> es la media del <span class="math inline">\(i-ésimo\)</span> nivel o tratamiento y <span class="math inline">\(\epsilon_{ij}\)</span> es un componente de error aleatorio que incorpora las otras fuentes de variabilidad en el experimento. Se supone además que los errores tienen media 0. La <a href="#eq-modmed" class="quarto-xref">Ecuación&nbsp;<span>8.1</span></a> recibe el nombre de <strong>modelo de medias</strong>.</p>
<p>Si definimos <span class="math inline">\(\mu_i=\mu+\alpha_i\)</span>, la <a href="#eq-modmed" class="quarto-xref">Ecuación&nbsp;<span>8.1</span></a> queda escrita de la forma:</p>
<p><span id="eq-modeff"><span class="math display">\[
y_{ij} = \mu + \alpha_i +  \epsilon_{ij} \quad \forall \; i,j
\tag{8.2}\]</span></span></p>
<p>En la <a href="#eq-modeff" class="quarto-xref">Ecuación&nbsp;<span>8.2</span></a> llamada comúnmente el <strong>modelo de efectos</strong>, el término <span class="math inline">\(\mu\)</span> es un parámetro para todos los tratamientos y se conoce como la <strong>media general</strong> y <span class="math inline">\(\alpha_i\)</span> es el efecto del tratamiento (nivel) <span class="math inline">\(i\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>¿Efectos fijos o aleatorios?
</div>
</div>
<div class="callout-body-container callout-body">
<p>La <a href="#eq-modeff" class="quarto-xref">Ecuación&nbsp;<span>8.2</span></a> tiene dos posibilidades.</p>
<ul>
<li>Los <span class="math inline">\(k\)</span> tratamientos fueron escogidos por el experimentador.</li>
<li>Los <span class="math inline">\(k\)</span> tratamientos fueron tomados de una muestra aleatoria de muchos tratamientos.</li>
</ul>
<p>En el primer caso, se puede probar la hipótesis sobre las medias de los tratamientos, y las conclusiones solo aplicarán a los niveles o tratamientos escogidos en el análisis. No se puede extender las conclusiones a tratamientos parecidos. Además es posible calcular los parámetros <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\alpha_i\)</span> y <span class="math inline">\(\sigma^2\)</span>. Este modelo se llama <strong>modelo de efectos fijos</strong>.</p>
<p>En el segundo caso las conclusiones que se basan en la muestra de tratamientos, se pueden extender a todos los tratamientos. En este caso los <span class="math inline">\(\alpha_i\)</span> son variables aleatorias. Por lo que conocer sus valores exactos no es necesariamente importante. Por otro lado, se pueden verificar hipótesis sobre la variabilidad de <span class="math inline">\(\alpha_i\)</span> y estimar el valor de esta variabilidad. Este modelo se llama <strong>modelo de efectos aleatorios</strong> o <strong>modelo de componentes de la varianza</strong>.</p>
</div>
</div>
</section>
<section id="tabla-anova" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="tabla-anova"><span class="header-section-number">8.3.2</span> Tabla ANOVA</h3>
<p>Sea <span class="math inline">\(\bar{y}\)</span> la media general, o media de todos los datos, y <span class="math inline">\(\bar{y_i}\)</span> la media por el grupo <span class="math inline">\(i-ésimo\)</span>. La suma cuadrática total está dada por</p>
<p><span id="eq-SCT"><span class="math display">\[
SCT = \sum_i{\sum_j{(y_{ij}-\bar{y})}^2}
\tag{8.3}\]</span></span></p>
<p>Esto mide la variación con respecto al centro de todos los datos. Un análisis de varianza divide <span class="math inline">\(SCT\)</span> en dos términos:</p>
<p><span id="eq-SCT2"><span class="math display">\[
SCT = \sum_i{\sum_j{(y_{ij}-\bar{y}_i)}^2} + \sum_i{n_i\left(\bar{y}_i-\bar{y}\right)^2}
\tag{8.4}\]</span></span></p>
<p>El primer término es la suma de los cuadrados del error (SCE). La suma <span class="math inline">\(\sum_j{(y_{ij}-\bar{y}_I)}^2\)</span>, mide la variación dentro del i-ésimo grupo. La suma de los cuadrados del error es entonces una medida de la variabilidad dentro de los grupos. El segundo término en la <a href="#eq-SCT2" class="quarto-xref">Ecuación&nbsp;<span>8.4</span></a> es llamada la suma cuadrática de los tratamientos (SCTr). La SCTr compara la media para cada grupo, <span class="math inline">\(\bar{y}_i\)</span>, con la media general. Esta mide la variabilidad entre las medias de las muestras. La <a href="#eq-SCT2" class="quarto-xref">Ecuación&nbsp;<span>8.4</span></a> se puede reescribir como</p>
<p><span id="eq-sct3"><span class="math display">\[
SCT = SCE + SCTr
\tag{8.5}\]</span></span></p>
<p>Si los datos provienen de una media común, esperaríamos que SCE y SCT sean aproximadamente iguales. Por otro lado si SCE y SCT son muy distintas, tendríamos evidencia contra la hipótesis nula. ¿Cómo podríamos decir si las diferencias se deben a que la hipótesis nula es falsa o unicámente a la variación muestral? El estadístico usado en este caso es:</p>
<p><span id="eq-fstat"><span class="math display">\[
F = \dfrac{\frac{SCTr}{k-1}}{\frac{SCE}{n-k}}
\tag{8.6}\]</span></span></p>
<p>Para obtener una escala adecuada, cada término se divide por sus respectivos grados de libertad, obteniendo la suma media de los cuadrado de los tratamientos o los errores (MCTr o MCE). <span class="math display">\[
MCTr=\frac{SCTr}{k-1}
\]</span></p>
<p><span class="math display">\[
MCE = \frac{SCE}{n-k}
\]</span> Los grados de libertad para SCT son <span class="math inline">\(n-1\)</span>, para <span class="math inline">\(SCE\)</span> los grados de libertad son <span class="math inline">\(n-k\)</span>. Usando <a href="#eq-sct3" class="quarto-xref">Ecuación&nbsp;<span>8.5</span></a> para los grados de libertad: <span class="math inline">\(gl(Total)=gl(Error)+gl(Tratamiento)\)</span> y reemplazando los grados de libertad totales y del error se obtiene que los grados de libertad de los tratamientos son <span class="math inline">\(k-1\)</span>. El procedimiento de la prueba se resume en la <strong>Tabla ANOVA</strong> que se muestra en la <a href="#tbl-anova" class="quarto-xref">Tabla&nbsp;<span>8.2</span></a></p>
<div id="tbl-anova" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.2: Tabla del Análisis de Varianza para el modelo de un único factor
</figcaption>
<div aria-describedby="tbl-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th>Fuente de Variación</th>
<th>Grados de Libertad</th>
<th>Suma de Cuadrados</th>
<th>Media Cuadrática</th>
<th><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entre tratamientos</td>
<td><span class="math inline">\(k-1\)</span></td>
<td><span class="math inline">\(SCTr = \sum_i{n_i\left(\bar{y}_i-\bar{y}\right)^2}\)</span></td>
<td><span class="math inline">\(MCTr=\frac{SCTr}{k-1}\)</span></td>
<td><span class="math inline">\(F=\frac{MCTr}{MCE}\)</span></td>
</tr>
<tr class="even">
<td>Error (dentro de los tratamientos)</td>
<td><span class="math inline">\(n-k\)</span></td>
<td><span class="math inline">\(SCE = \sum_i{\sum_j{(y_{ij}-\bar{y}_i)}^2}\)</span></td>
<td><span class="math inline">\(MCE = \frac{SCE}{n-k}\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(n-1\)</span></td>
<td><span class="math inline">\(SCT = \sum_i{\sum_j{(y_{ij}-\bar{y})}^2}\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="diseño-completo-al-azar" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="diseño-completo-al-azar"><span class="header-section-number">8.4</span> Diseño completo al azar</h2>
<p>El diseño experimental más sencillo es un diseño completamente al azar. Este funciona mejor en situaciones muy controladas y condiciones muy uniformes. Por este motivo, el diseño completamente al azar no se suele utilizar en experimentos de campo. Puede utilizarlo si trabaja en un campo muy uniforme, en un invernadero o en una cámara de crecimiento, o si no tiene idea de las condiciones de cultivo. de crecimiento, o de la variabilidad de su campo.</p>
<p>El modelo matemático para los datos provenientes de un diseño completo al azar, con un número diferente de repeticiones para cada nivel del factor puede ser escrito como;</p>
<p><span class="math display">\[
y_{ij} = \mu +\alpha_i + \epsilon_{ij}
\]</span></p>
<p>La tabla ANOVA correspondiente a este modelo es la mostrada en <a href="#tbl-anova" class="quarto-xref">Tabla&nbsp;<span>8.2</span></a>.</p>
<p>En el <a href="02-estdesc.html#exr-siete" class="quarto-xref">Ejercicio&nbsp;<span>3.11</span></a>, se presentó el proyecto de graduación de Alfredo Aguilar y José C. Flores, a modo de ejemplo vamos a analizar los datos correspondientes a la última medición para verificar la existencia de diferencias significativas para la altura entre los tratamientos. Para esto inicialmente se va a crear la variable DDS que era una de las actividades que se debía realizar en el ejercicio mencionado, posteriormente se filtrarán los datos para quedarnos unicámente con las observaciones donde la variable DDS sea igual a 56.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>datos24004 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"datos/datos24004.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"datos"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>datos24004 <span class="ot">&lt;-</span> datos24004 <span class="sc">|&gt;</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">DDS =</span> <span class="fu">as.numeric</span>(Fecha <span class="sc">-</span> Siembra)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>dds56 <span class="ot">&lt;-</span> datos24004 <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    DDS <span class="sc">==</span> <span class="dv">56</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finalmente vamos a hacer la prueba ANOVA con la función <code>aov()</code>, la forma de usar la función es: <code>aov(formula, data)</code>. El resultado lo guardamos en una variable y para ver los resultados se usa la función <code>summary()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Altura <span class="sc">~</span> Tratamiento, <span class="at">data =</span> dds56)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Tratamiento  6   3965   660.8   1.257  0.284
Residuals   98  51518   525.7               </code></pre>
</div>
</div>
<p>Se observa que <span class="math inline">\(SCTr \; (3965) &lt; SCE \; (51518)\)</span>, esto sugiere que <strong>la mayor parte de la variabilidad en la altura no se explica por los tratamientos</strong>. El valor <span class="math inline">\(p\)</span> de la prueba ANOVA es 0.2844 que es mayor a la siginificancia de <span class="math inline">\(0.05\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Comparamos el valor <span class="math inline">\(p\)</span> contra la <span class="math inline">\(\alpha = 0.05\)</span> por convención y porque funciona muy bien como equilibrio. Siempre es recomendable preguntarse:</p>
<p><strong>¿Qué es más grave en este contexto: rechazar una hipótesis verdadera o no detectar una diferencia real?</strong></p>
<p>Como dato histórico. Ronald Fisher, uno de los padres de la estadística moderna, propuso <span class="math inline">\(0.05\)</span> como un umbral práctico.</p>
</div>
</div>
<p>De acuerdo con el valor <span class="math inline">\(p\)</span>, se concluye que no hay evidencia suficiente para afirmar que los tratamientos afectan signficativamente la altura. Las diferencias observadas entre tratamientos podrían explicarse por variabilidad aleatoria.</p>
<p>Ahora vamos a trabajar con datos del mismo proyecto, pero del rendimiento en toneladas por hectárea de cada tratamiento. En la hoja <code>rendimiento_ha</code> del archivo <code>rend_24004.xlsx</code> se encuentran los datos, las variables presentes en el archivo son:</p>
<ul>
<li><strong>Tratamiento</strong>: tratamiento al que se sometió la parcela.</li>
<li><strong>Parcela</strong>: número de parcela</li>
<li><strong>peso_promedio</strong>: peso de las mazorcas en gramos.</li>
<li><strong>plantas_hectarea</strong>: número de plantas estimadas por hectárea.</li>
<li><strong>Rendimiento_ha</strong>: rendimiento en toneladas por hectárea (t/ha)</li>
</ul>
<p>Primero, cargamos los datos. Se resumen los datos, este resumen se presenta en la <a href="#tbl-rendaj" class="quarto-xref">Tabla&nbsp;<span>8.3</span></a>. Además se crea un diagrama de cajas, dicho diagrama se presenta en la <a href="#fig-rendaj" class="quarto-xref">Figura&nbsp;<span>8.1</span></a>. De acuerdo a lo que se observa en la tabla y en la figura, el tratamiento T2 tiene el mayor rendimiento promedio mientras que T6 y T7 tienen medias menores al resto de los tratamientos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>rend24004 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"datos/rend_24004.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"rendimiento_ha"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>resu_rend <span class="ot">&lt;-</span> rend24004 <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Tratamiento) <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">mean</span>(Rendimiento_ha),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Desv =</span> <span class="fu">sd</span>(Rendimiento_ha)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div id="tbl-rendaj" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rendaj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.3: Estadística descriptiva del rendimiento
</figcaption>
<div aria-describedby="tbl-rendaj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Tratamiento</th>
<th style="text-align: right;">Media</th>
<th style="text-align: right;">Desv</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T1</td>
<td style="text-align: right;">10.231230</td>
<td style="text-align: right;">2.986958</td>
</tr>
<tr class="even">
<td style="text-align: left;">T2</td>
<td style="text-align: right;">14.919665</td>
<td style="text-align: right;">3.121122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T3</td>
<td style="text-align: right;">10.313008</td>
<td style="text-align: right;">3.182815</td>
</tr>
<tr class="even">
<td style="text-align: left;">T4</td>
<td style="text-align: right;">10.076396</td>
<td style="text-align: right;">1.912941</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T5</td>
<td style="text-align: right;">10.979170</td>
<td style="text-align: right;">3.235731</td>
</tr>
<tr class="even">
<td style="text-align: left;">T6</td>
<td style="text-align: right;">7.888415</td>
<td style="text-align: right;">2.855456</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T7</td>
<td style="text-align: right;">6.650138</td>
<td style="text-align: right;">1.648281</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rendaj" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rendaj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-DOE_files/figure-html/fig-rendaj-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rendaj-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8.1: Rendimiento por tratamiento
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ahora procedemos a hacer la prueba ANOVA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Rendimiento_ha <span class="sc">~</span> Tratamiento, <span class="at">data =</span> rend24004)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Tratamiento  6    245   40.84   5.314 0.000552 ***
Residuals   35    269    7.68                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Podemos apreciar que <span class="math inline">\(SCTr\)</span> es muy similar a <span class="math inline">\(SCE\)</span>, lo que nos sugiere que los tratamientos están explicando una parte importante de la variabilidad del rendimiento. El valor <span class="math inline">\(p\)</span> es muy bajo, inclusive menor que <span class="math inline">\(0.001\)</span>. Hay suficiente evidencia estadística para rechazar la hipótesis nula. Se concluye que, los tratamientos tienen un efecto significativo sobre el rendimiento. Dicho de otra forma, al menos uno de los tratamientos presenta una media significativamente distinta respecto a los demás.</p>
<p>¿Qué ocurre cuando la prueba ANOVA es significativa? ¿Cómo averigüar dónde se encuentran las diferencias significativas?</p>
</section>
<section id="pruebas-de-comparaciones-múltiples-para-la-media." class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="pruebas-de-comparaciones-múltiples-para-la-media."><span class="header-section-number">8.5</span> Pruebas de comparaciones múltiples para la media.</h2>
<p>Cuando la prueba ANOVA es estadísticamente significativa, el paso posterior consiste en buscar entre qué grupos, poblaciones o tratamientos existen diferencias. En algunos casos el investigador podría tener comparaciones planificadas que desea hacer; en otras situaciones podría no tener idea de que comparaciones debe hacer. En el primer caso se habla de <strong>contrastes planificados o <em>a priori</em></strong>, en el segundo caso nos referimos a <strong>contrastes múltiples o <em>a posteriori</em></strong>.</p>
<section id="contrastes-a-priori" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="contrastes-a-priori"><span class="header-section-number">8.5.1</span> Contrastes <em>a priori</em></h3>
<p>Los <strong>contrastes</strong> son combinaciones lineales de medias que permiten evaluar hipótesis específicas sobre los tratamientos o grupos. Los <strong>contrastes planificados</strong> se definen antes de observar los datos, con base en hipótesis sustentadas teóricamente.</p>
<section id="contrastes-ortogonales" class="level4" data-number="8.5.1.1">
<h4 data-number="8.5.1.1" class="anchored" data-anchor-id="contrastes-ortogonales"><span class="header-section-number">8.5.1.1</span> Contrastes ortogonales</h4>
<p>Los contrastes son <strong>ortogonales</strong> cuando son <strong>independientes entre sí</strong> es decir, no existe superposición en la información que aportan. Desde el punto de vista matemático, dos contrastes <span class="math inline">\(C_1\)</span> y <span class="math inline">\(C_2\)</span>, con coeficientes <span class="math inline">\(c_{1i}\)</span> y <span class="math inline">\(c_{2i}\)</span>, son ortogonales si se cumple:</p>
<p><span class="math display">\[
\sum_{i=1}^k c_{1i} \cdot c_{2i} = 0
\]</span></p>
<p>donde <span class="math inline">\(k\)</span> es un número de grupos. Esto garantiza que cada contraste evalúe un aspecto distinto de las diferencias entre grupos, sin redundancia.</p>
<section id="reglas-para-definir-contrastes-ortogonales." class="level5" data-number="8.5.1.1.1">
<h5 data-number="8.5.1.1.1" class="anchored" data-anchor-id="reglas-para-definir-contrastes-ortogonales."><span class="header-section-number">8.5.1.1.1</span> Reglas para definir contrastes ortogonales.</h5>
<ol type="1">
<li>Los coeficientes de cada contraste deben sumar cero:</li>
</ol>
<p><span class="math display">\[
\sum c_i = 0
\]</span></p>
<ol start="2" type="1">
<li>Los productos cruzados de coeficientes entre pares de contrastes deben sumar cero:</li>
</ol>
<p><span class="math display">\[
\sum c_{1i} \cdot c_{2i} = 0
\]</span></p>
<ol start="3" type="1">
<li>Se pueden definir máximo <span class="math inline">\(k-1\)</span> contrastes ortogonales si hay <span class="math inline">\(k\)</span> grupos.</li>
</ol>
</section>
</section>
<section id="contrastes-polinomiales" class="level4" data-number="8.5.1.2">
<h4 data-number="8.5.1.2" class="anchored" data-anchor-id="contrastes-polinomiales"><span class="header-section-number">8.5.1.2</span> Contrastes polinomiales</h4>
<p>Los <strong>contrastes polinomiales</strong> son un caso especial de contrastes ortogonales que se utilizan cuando los <strong>niveles del factor están ordenados cuantitativamente</strong> (por ejemplo, dosis de un fertilizante, niveles de estrés, tiempo de exposición, etc.). Sirven para detectar tendencias como efectos lineales, cuadráticos o cúbicos en los datos.</p>
<p>Los contrastes polinomiales son una técnica utilizada en el contexto del análisis de varianza (ANOVA) cuando los tratamientos o niveles del factor tienen un <strong>orden natural</strong> y están <strong>espaciados regularmente</strong> (por ejemplo, 0, 1, 2, 3 unidades). Su objetivo es identificar si la relación entre los niveles del factor y la media de respuesta sigue una tendencia lineal, cuadrática, cúbica, etc.</p>
<p>Los contrastes polinomiales son muy comunes en estudios de:</p>
<p>Son contrastes ortogonales construidos a partir de funciones polinomiales. Cada constante representa una tendencia específica:</p>
<ul>
<li><strong>Lineal</strong>: verifica si hay un aumento o disminución constante.</li>
<li><strong>Cuadrático</strong>: sirve para detectar curvaturas.</li>
<li><strong>Cúbico</strong>: detecta cambios más complejos en la pendiente.</li>
<li>El polinomio puede tener máximo grado <span class="math inline">\(k-1\)</span>, donde <span class="math inline">\(k\)</span> es el número de niveles del factor.</li>
</ul>
<p>Para construir contrastes polinomiales, el factor debe ser <strong>cuantitativo</strong> u <strong>ordinal</strong> con niveles <strong>equiespaciados</strong>, además debe haber el mismo número de observaciones por tratamiento o grupo. Los contrastes polinomiales cumplen con la ortogonalidad entre ellos.</p>
</section>
</section>
<section id="contrastes-a-posteriori" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="contrastes-a-posteriori"><span class="header-section-number">8.5.2</span> Contrastes <em>a posteriori</em></h3>
<section id="clasificación-de-pruebas-de-comparación-múltiple-de-medias" class="level4" data-number="8.5.2.1">
<h4 data-number="8.5.2.1" class="anchored" data-anchor-id="clasificación-de-pruebas-de-comparación-múltiple-de-medias"><span class="header-section-number">8.5.2.1</span> Clasificación de Pruebas de Comparación Múltiple de Medias</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Criterio</strong></th>
<th><strong>Tipo de Prueba</strong></th>
<th><strong>Ejemplos</strong></th>
<th><strong>Características principales</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Propósito</strong></td>
<td>Pruebas a priori (planeadas)</td>
<td>Contrastes ortogonales, polinomiales</td>
<td>Se planifican antes del análisis. Mayor potencia estadística.</td>
</tr>
<tr class="even">
<td></td>
<td>Pruebas a posteriori (no planeadas)</td>
<td>Tukey HSD, Bonferroni, Duncan, LSD, Scheffé</td>
<td>Se aplican tras ANOVA significativa. Controlan error tipo I por comparaciones múltiples.</td>
</tr>
<tr class="odd">
<td><strong>Control del Error Tipo I</strong></td>
<td>Estricto</td>
<td>Bonferroni, Holm</td>
<td>Muy conservadoras. Reducen el riesgo de falsos positivos.</td>
</tr>
<tr class="even">
<td></td>
<td>Moderado</td>
<td>Tukey HSD, Scheffé</td>
<td>Buen equilibrio entre control de error y potencia.</td>
</tr>
<tr class="odd">
<td></td>
<td>Laxo</td>
<td>Fisher LSD, Duncan</td>
<td>Mayor riesgo de error tipo I. Más potentes pero menos conservadoras.</td>
</tr>
<tr class="even">
<td><strong>Número de Comparaciones</strong></td>
<td>Comparaciones por pares</td>
<td>Tukey HSD, LSD, Duncan</td>
<td>Comparan todas las medias de dos en dos.</td>
</tr>
<tr class="odd">
<td></td>
<td>Comparaciones con un control o grupo de referencia</td>
<td>Dunnett, contrastes planeados</td>
<td>Comparan grupos experimentales con un grupo base.</td>
</tr>
<tr class="even">
<td><strong>Supuestos estadísticos</strong></td>
<td>Igualdad de varianzas (homocedasticidad)</td>
<td>Tukey HSD, Bonferroni, Scheffé</td>
<td>Requieren homogeneidad de varianzas (revisar con pruebas como Levene).</td>
</tr>
<tr class="odd">
<td></td>
<td>Sin igualdad de varianzas (heterocedasticidad)</td>
<td>Games-Howell, Tamhane’s T2</td>
<td>Usadas cuando no se cumple la homocedasticidad.</td>
</tr>
<tr class="even">
<td><strong>Tipo de contraste</strong></td>
<td>Paramétricas</td>
<td>Tukey, Bonferroni, Scheffé, LSD</td>
<td>Requieren normalidad y homocedasticidad.</td>
</tr>
<tr class="odd">
<td></td>
<td>No paramétricas</td>
<td>Pruebas de Dunn, Nemenyi, Conover</td>
<td>Se aplican cuando no se cumplen los supuestos paramétricos.</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="diseño-de-bloques-completos-al-azar" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="diseño-de-bloques-completos-al-azar"><span class="header-section-number">8.6</span> Diseño de bloques completos al azar</h2>
</section>
<section id="diseño-de-cuadro-latino" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="diseño-de-cuadro-latino"><span class="header-section-number">8.7</span> Diseño de cuadro latino</h2>
</section>
<section id="pruebas-no-paramétricas-equivalentes-al-análisis-de-varianza" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="pruebas-no-paramétricas-equivalentes-al-análisis-de-varianza"><span class="header-section-number">8.8</span> Pruebas no paramétricas equivalentes al análisis de varianza</h2>
</section>
<section id="pruebas-de-comparaciones-múltiples-no-paramétricas" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="pruebas-de-comparaciones-múltiples-no-paramétricas"><span class="header-section-number">8.9</span> Pruebas de comparaciones múltiples no paramétricas</h2>
</section>
<section id="diseño-factorial" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="diseño-factorial"><span class="header-section-number">8.10</span> Diseño factorial</h2>
</section>
<section id="ejercicios" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ejercicios">Ejercicios</h2>
<div id="exr-doe1" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.1</strong></span> Con los datos y el proyecto del <a href="02-estdesc.html#exr-seis" class="quarto-xref">Ejercicio&nbsp;<span>3.10</span></a>. Resuelva las siguientes cuestiones.</p>
</div>
<ol type="a">
<li>¿Existen diferencias significativas para la altura por variedad en la primera medición?</li>
<li>¿Existen diferencias significativas para la altura por variedad en la segunda medición?</li>
<li>¿Existen diferencias significativas para el diámetro por variedad en la tercera medición?</li>
<li>¿Existen diferencias significativas para el diámetro por variedad en la cosecha?</li>
<li>Crear un conjunto llamado <em>basetotal</em> que contenga los datos previos a la cosecha y de la cosecha. Para lograr esto siga los siguientes pasos.</li>
</ol>
<ul>
<li>Cree el conjunto <em>datosmaiz2</em> a partir de <em>datosmaiz</em>, en este conjunto debe renombrar las variables <em>Medicion</em> y <em>Diametro</em> como <em>Medición</em> y <em>Diámetro</em> respectivamente. Además debe crear la variable <em>DDS</em> que sea 15 cuando <em>Medición</em> sea igual a 1, 30 cuando <em>Medición</em> sea igual a 2 y 45 cuando <em>Medición</em> sea igual a 2. Por último remueva la variable <em>Fecha</em>.</li>
<li>Cree el conjunto <em>cosecha2</em> a partir de <em>cosecha</em>. En este conjunto cree la variable <em>Medición</em> que tomará el valor de 4 y la variable <em>DDS</em> que tomará el valor de 91.</li>
<li>Finalmente una <em>datosmaiz2</em> y <em>cosecha2</em> para crear el conjunto <em>basetotal</em>.</li>
</ul>
<ol start="6" type="a">
<li>Verifique la existencia de diferencias significativas en las alturas por variedad. Realice esta verificación para todas las mediciones y guarde los resultados en la tabla <em>valorespalt</em>.</li>
<li>Verifique la existencia de diferencias significativas en los diámetros por variedad. Realice esta verificación para todas las mediciones y guarde los resultados en la tabla <em>valorespdiam</em>.</li>
<li>Guarde las tablas <em>valorespalt</em> y <em>valorespdiam</em> en un libro llamado <em>anova_alt_diam.xlsx</em>. Las hojas de este libro se deben llamar <em>altura</em> y <em>diametro</em> respectivamente.</li>
</ol>
<div id="exr-doe2" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.2</strong></span> Con los datos y el proyecto del <a href="02-estdesc.html#exr-quin3" class="quarto-xref">Ejercicio&nbsp;<span>3.8</span></a>, resolver las siguientes cuestiones.</p>
</div>
<ol type="a">
<li>Crear un archivo llamado <em>reporte_GAGS.qmd</em></li>
<li>Cargar los paquetes <em>agricolae</em>, <em>tidyverse</em>, <em>writexl</em>, <em>readxl</em> y <em>jtools</em>.</li>
<li>Cargar los datos almacenados en el archivo de Excel, los datos deben ser almacenados en una variable llamada <em>data23035</em>.</li>
<li>Crear una variable llamada <strong>Diámetro</strong>. Esta variable es el promedio del diámetro horizontal y el diámetro vertical.</li>
<li>Seleccione los datos hasta la semana 8.</li>
<li>Para evitar el efecto borde, Gabriela solamentes incluyó en su análisis las plantas 6, 7, 10 y 11. Seleccione estas plantas para realizar el análisis. <strong>Nota: Para realizar las dos últimas tareas debe usar la función <em>filter</em> y combinarlas con un operador lógico adecuado.</strong></li>
<li>Con un título de nivel 2, crear una sección dentro del reporte llamada <strong><em>Análisis de la variable Altura</em></strong></li>
<li>Con un título de nivel 3, crear una sección dentro del reporte llamada <strong><em>Análisis descriptivo</em></strong></li>
<li>Crear una tabla llamada <em>stats_alt</em> que resuma la altura por semana y por tratamiento:</li>
</ol>
<ul>
<li>La media y la desviación de la altura.</li>
<li>El valor crítico de la distribución <span class="math inline">\(t\)</span> para el número de observaciones calculado con un <span class="math inline">\(95\%\)</span> de confianza.</li>
<li>El error estándar de la media de la altura.</li>
<li>Los extremos del intervalo del <span class="math inline">\(95\%\)</span> de confianza para la media de la altura.</li>
<li>Esta tabla no debe ser mostrada en el reporte.</li>
</ul>
<ol start="10" type="a">
<li>Con ayuda de la tabla <em>stats_alt</em> crear un gráfico de evolución de la altura a lo largo de las semanas, incluya barras de error con los extremos del intervalo de confianza. Separe las líneas por tratamiento. En la carpeta gráficos guardar el gráfico generado con el nombre <em>evol_alt.png</em>. Interpretar el gráfico generado.</li>
<li>Con un título de nivel 3, crear una sección dentro del reporte llamada <strong><em>Análisis inferencial</em></strong>.</li>
<li>En la primera semana ¿existen diferencias significativas en la altura promedio por tratamiento? Para contestar esta pregunta muestre el resultado de la prueba ANOVA.</li>
<li>En las 8 semanas ¿existen diferencias significativas en la altura promedio por tratamiento? Para contestar esta pregunta muestre los valores <span class="math inline">\(p\)</span> de las pruebas ANOVA. Se recomienda trabajar con el siguiente flujo de trabajo:</li>
</ol>
<ul>
<li>Realizar la prueba ANOVA por semana para la comparación de la altura promedio por tratamiento, en una tabla llamada <em>valsp_aov_alt</em> guardar los valores <span class="math inline">\(p\)</span> de cada prueba ANOVA.</li>
<li>Modificar la tabla <em>stats_alt</em> para que quede como se muestra en la <a href="#tbl-doe2" class="quarto-xref">Tabla&nbsp;<span>8.4</span></a>, el resultado guardarlo en una variable llamada <em>stats_alt2</em>:</li>
</ul>
<div id="tbl-doe2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-doe2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.4: Tabla modelo 1.
</figcaption>
<div aria-describedby="tbl-doe2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Semana</th>
<th>T1</th>
<th>T2</th>
<th>T3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(\bar{x}_{T1-1} \pm s_{T1-1}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-1} \pm s_{T2-1}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-1} \pm s_{T3-1}\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(\bar{x}_{T1-2} \pm s_{T1-2}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-2} \pm s_{T2-2}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-2} \pm s_{T3-2}\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td>7</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>8</td>
<td><span class="math inline">\(\bar{x}_{T1-8} \pm s_{T1-8}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-8} \pm s_{T2-8}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-8} \pm s_{T3-8}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ul>
<li>Utilizar la función <em>left_join()</em> para unir las tablas <em>stats_alt2</em> y <em>valsp_aov_alt</em>, el resultado guardarlo en una tabla llamada <em>stats_alt3</em>, un ejemplo de la tabla se muestra en la <a href="#tbl-doe2_1" class="quarto-xref">Tabla&nbsp;<span>8.5</span></a> .En el reporte se debe incluir esta última tabla.</li>
</ul>
<div id="tbl-doe2_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-doe2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.5: Tabla modelo 2.
</figcaption>
<div aria-describedby="tbl-doe2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Semana</th>
<th>T1</th>
<th>T2</th>
<th>T3</th>
<th>Valor <span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(\bar{x}_{T1-1} \pm s_{T1-1}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-1} \pm s_{T2-1}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-1}\pm s_{T3-1}\)</span></td>
<td><span class="math inline">\(pval_1\)</span></td>
</tr>
<tr class="even">
<td>2</td>
<td><span class="math inline">\(\bar{x}_{T1-2} \pm s_{T1-2}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-2}\pm s_{T2-2}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-2}\pm s_{T3-2}\)</span></td>
<td><span class="math inline">\(pval_2\)</span></td>
</tr>
<tr class="odd">
<td>3</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>4</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>6</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="odd">
<td>7</td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
<td><span class="math inline">\(\dots\)</span></td>
</tr>
<tr class="even">
<td>8</td>
<td><span class="math inline">\(\bar{x}_{T1-8}\pm s_{T1-8}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T2-8}\pm s_{T2-8}\)</span></td>
<td><span class="math inline">\(\bar{x}_{T3-8}\pm s_{T3-8}\)</span></td>
<td><span class="math inline">\(pval_8\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ol start="14" type="a">
<li>Guardar esta la tabla en la carpeta <em>resultados</em> en un archivo llamado <em>altura.xlsx</em>.</li>
<li>Escribir las conclusiones de esta última tabla.</li>
</ol>
<div id="exr-doe3" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.3</strong></span> Con los datos y el proyecto del <a href="#exr-doe1" class="quarto-xref">Ejercicio&nbsp;<span>8.1</span></a>, resuelva las siguientes cuestiones.</p>
</div>
<ol type="a">
<li>Usando las pruebas de Fisher, Tukey, Bonferroni y Scheffé determine dónde se encuentran las diferencias de las alturas en la primera medición.</li>
<li>Usando las pruebas de Fisher, Tukey, Bonferroni y Scheffé determine dónde se encuentran las diferencias de las alturas en la segunda medición.</li>
<li>Cree un objeto llamado <em>grpsaltm2</em> que contenga las columnas <em>Variedad</em>, <em>Medición</em> y <em>Grupos</em>. Para esto siga los siguientes pasos:</li>
</ol>
<ul>
<li>Guarde el resultado de la prueba de Fisher para la segunda medición de la altura en un objeto llamado <em>compaltm2</em>.</li>
<li>Extraiga los grupos de la comparación hecha en el paso anterior y almacenelos en la variable <em>grpsaltm2</em>.</li>
<li>Modifique el objeto <em>grpsaltm2</em>, para esto cambie los nombres de fila a una variable con el nombre <em>Variedad</em>, luego cree una columna llamada <em>Medición</em> que tenga el número 2, remueva la columna de la Altura y finalmente renombre la columna <em>groups</em> con el nombre <em>Grupos</em>.</li>
</ul>
<ol start="4" type="a">
<li>Usando la prueba de Fisher realice las comparaciones múltiples de las medias de las alturas por variedad para cada medición.</li>
<li>Para la medición 2, grafique un diagrama de caja de la altura por medición. En este gráfico muestre además los grupos de la prueba de Fisher en la parte superior de las cajas.</li>
<li>Para todas las mediciones, grafique un diagrama de caja de la altura por medición. En cada gráfico muestre además los grupos de la prueba de Fisher en la parte superior de las cajas. Guarde cada uno de los gráficos con los nombres <em>boxaltM1.png</em>, <em>boxaltM2.png</em>, <em>boxaltM3.png</em> y <em>boxaltM4.png</em> respectivamente para cada medición.</li>
</ol>
<div id="exr-doe4" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.4</strong></span> Con los datos y el proyecto del ejercicio <a href="#exr-doe2" class="quarto-xref">Ejercicio&nbsp;<span>8.2</span></a> resolver las siguientes cuestiones.</p>
</div>
<ol type="a">
<li>Para la semana 1, utilizando la prueba de Fisher ¿dónde se encuentran las diferencias significativas?</li>
<li>Para la semana 1, utilizando la prueba de Tukey ¿dónde se encuentran las diferencias significativas?</li>
<li>Para la semana 1, utilizando la prueba de Bonferroni ¿dónde se encuentran las diferencias significativas?</li>
<li>Para la semana 6, utilizando la prueba de Fisher ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Para la semana 7, utilizando la prueba de Fisher ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Para la semana 6, utilizando la prueba de Tukey ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Para la semana 7, utilizando la prueba de Tukey ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Para la semana 6, utilizando la prueba de Bonferroni ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Para la semana 7, utilizando la prueba de Bonferroni ¿es posible encontrar dónde están las diferencias significativas?</li>
<li>Utilizando la prueba de Tukey, determine dónde se encuentran las diferencias significativas desde la semana 1 hasta la semana 8. Presente estos resultados en una tabla adecuada.</li>
</ol>
<div id="exr-doe5" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.5</strong></span> El proyecto de Mark Norman y Daniel Kasawa tenía como objetivo desarrollar un producto herbicida preemergente con la doble funcionalidad del biochar y la pendimetalina. El producto se administró en forma de pellets y en polvo para evaluar su eficacia relativa, la eficacia en el control de las malezas y su impacto en el crecimiento del maíz. El experimento abarcó seis tratamientos distintos distribuidos aleatoriamente en varias parcelas, cada uno de ellos sometido a cuatro repeticiones. El estudio incorporó dos bloques: uno con aplicación previa de biochar (A) y otro desprovisto de cualquier tratamiento con biochar (B). Los tratamientos usados fueron:</p>
<ul>
<li><strong>T1</strong>: NPK (10-30-10)</li>
<li><strong>T2</strong>: NPK (10-30-10) + Pendimetalina</li>
<li><strong>T3</strong>: Biochar (pellet) + NPK (10-30-10) + Pendimetalina (incorporada en el biochar)</li>
<li><strong>T4</strong>: Biochar (polvo) + NPK (10-30-10) + Pendimetalina (incorporada en el biochar)</li>
<li><strong>T5</strong>: Biochar (pellet) + NPK (10-30-10) + Pendimetalina (rociada en el suelo)</li>
<li><strong>T6</strong>: Biochar (polvo) + NPK (10-30-10) + Pendimetalina (rociada en el suelo)</li>
</ul>
<p>En la hoja <em>biomass</em> del archivo <em>data_MN_DK.xlsx</em> se encuentran los datos a ser analizados en este ejercicio, adicionalmente en la hoja <em>dict_biomass</em> se incluyen las etiquetas para las variables <em>Leaves</em>, <em>Height</em> y <em>Diameter</em>. Las variables presentes en la hoja <em>biomass</em> son:</p>
<ul>
<li><strong>Date</strong>: fecha de la medición.</li>
<li><strong>Measurement</strong>: número de medición.</li>
<li><strong>Treatment</strong>: tratamiento.</li>
<li><strong>Block</strong>: bloque en el que se realizó la medición.</li>
<li><strong>Repetition</strong>: repetición. Para cada repetición se tomaron 3 mediciones.</li>
<li><strong>Leaves</strong>: número de hojas.</li>
<li><strong>Height</strong>: altura de la planta en centímetros.</li>
<li><strong>Diameter</strong>: diámetro de la planta en milímetros.</li>
</ul>
</div>
<ol type="a">
<li>Cree un proyecto llamado <em>Pg_MN_DK</em>.</li>
<li>Cargue los datos de las hojas <em>biomass</em> y <em>dict_biomass</em>.</li>
<li>Para cada repetición se tomaron 3 mediciones, es decir que se debe calcular el promedio de las 3 mediciones para tener el valor de cada repetición. Utilizando la función <code>summarise_at</code>, calcule la media de las 3 mediciones para cada repetición.</li>
<li>Daniel y Mark tuvieron problemas con los datos del tratamiento 3, repetición 2, bloque B por lo que decidieron eliminar estos datos del análisis. Filtre los datos para poder realizar esta tarea.</li>
<li>La variable <strong>Measurement</strong> no está relacionada con las fechas en que se tomaron los datos. Crear una variable llamada <strong>Measurement</strong> a partir de la variable <strong>Date</strong>.</li>
<li>Utilizando la función <code>pivot_longer</code>, transforme los datos de formato ancho a formato largo. Las columnas que deben ser transformadas son <strong>Leaves</strong>, <strong>Height</strong> y <strong>Diameter</strong>. Los nombres de las variables deben ser guardados en una variable llamada <strong>Variable</strong> y los valores en una variable llamada <strong>Value</strong>. Adicionalmente crear una variable llamada <strong>Week</strong> que sea igual al doble del número de medición.</li>
<li>Crear las siguientes tablas:</li>
</ol>
<ul>
<li><code>stats_all_long_trt_bl</code>: estadísticas agrupando por medición, semana, tratamiento, bloque y variable.</li>
<li><code>stats_all_long_bl</code>: estadísticas agrupando por medición, semana, bloque y variable.</li>
<li><code>stats_all_long_trt</code>: estadísticas agrupando por medición, semana, tratamiento y variable.</li>
</ul>
<p>Todas las tablas deben contener:</p>
<ul>
<li>La media y la desviación de la altura.</li>
<li>El valor crítico de la distribución <span class="math inline">\(t\)</span> para el número de observaciones calculado con un <span class="math inline">\(95\%\)</span> de confianza.</li>
<li>El error estándar de la media de la altura.</li>
<li>Los extremos del intervalo del <span class="math inline">\(95\%\)</span> de confianza para la media de la altura.</li>
</ul>
<ol start="8" type="a">
<li>Realice la prueba ANOVA para cada medición para verificar si existen diferencias significativas por tratamiento, tomando en cuenta el bloque. Posteriormente realice la prueba de Bonferroni para verificar donde se encuentran las diferencias significativas. En un objeto llamado <code>groups_trt</code> almacene los grupos resultantes de realizar la prueba de Bonferroni por tratamiento y en un objeto llamado <code>groups_block</code> almacene los grupos resultantes de realizar la prueba de Bonferroni por bloque. Con ayuda de la función <code>left_join</code> una estos dos objetos con las tablas <code>stats_all_long_trt</code> y <code>stats_all_long_bl</code> respectivamente.</li>
<li>Con la función <code>dir.create</code> crear una subcarpeta llamada <strong>biomass</strong> dentro de la carpeta <strong>graficos</strong>. Dentro de esta carpeta, guarde para cada variable dentro de cada bloque un gráfico de líneas y un diagrama de cajas. En la carpeta <strong>biomass</strong> deben existir 12 gráficos.</li>
<li>Con la función <code>dir.create</code> crear una subcarpeta llamada <strong>blocks</strong> dentro de la carpeta <strong>biomass</strong> creada en el literal anterior. Dentro de esta carpeta, guarde para cada variable separados bloque un gráfico de líneas y un diagrama de cajas. En la carpeta <strong>blocks</strong> deben existir 6 gráficos.</li>
<li>A partir de la tabla <code>stats_all_long_bl</code>, generar una tabla como la <a href="#tbl-mod1dkmn" class="quarto-xref">Tabla&nbsp;<span>8.6</span></a> y guardarla en <code>stats_all_long_bl2</code>, esta última tabla debe tener 12 filas y 4 columnas. A partir de la tabla <code>stats_all_long_trt</code> generar una tabla como la <a href="#tbl-mod2dkmn" class="quarto-xref">Tabla&nbsp;<span>8.7</span></a> y guardarla en <code>stats_all_long_trt2</code>, esta última tabla debe tener 12 filas y 8 columnas.</li>
<li>Guardar las dos tablas del literal anterior en un archivo llamado <strong>stats_biomass.xlsx</strong>, en hojas llamadas <strong>Blocks</strong> y <strong>Treatments</strong> respectivamente.</li>
</ol>
<div id="tbl-mod1dkmn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mod1dkmn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.6: Tabla modelo 1
</figcaption>
<div aria-describedby="tbl-mod1dkmn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Week</th>
<th>Variable</th>
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>Diameter</td>
<td><span class="math inline">\(\mu_{W2-DA} \pm \sigma_{W2-DA}\)</span> grupo</td>
<td><span class="math inline">\(\mu_{W2-DB} \pm \sigma_{w2-DB}\)</span> grupo</td>
</tr>
<tr class="even">
<td>2</td>
<td>Height</td>
<td><span class="math inline">\(\mu_{W2-HA} \pm \sigma_{W2-HA}\)</span> grupo</td>
<td><span class="math inline">\(\mu_{W2-HB} \pm \sigma_{W2-HB}\)</span> grupo</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td>8</td>
<td>Diameter</td>
<td><span class="math inline">\(\mu_{W8-DA} \pm \sigma_{W8-DA}\)</span> grupo</td>
<td><span class="math inline">\(\mu_{W8-DB} \pm \sigma_{W8-DB}\)</span> grupo</td>
</tr>
<tr class="odd">
<td>8</td>
<td>Height</td>
<td><span class="math inline">\(\mu_{W8-HA} \pm \sigma_{W8-HA}\)</span> grupo</td>
<td><span class="math inline">\(\mu_{W8-HB} \pm \sigma_{W8-HB}\)</span> grupo</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-mod2dkmn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mod2dkmn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;8.7: Tabla modelo 2
</figcaption>
<div aria-describedby="tbl-mod2dkmn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 40%">
<col style="width: 6%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Week</th>
<th>Variable</th>
<th>T1</th>
<th><span class="math inline">\(\ldots\)</span></th>
<th>T6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>Diameter</td>
<td><span class="math inline">\(\mu_{W2-DT1} \pm \sigma_{W2-DT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W2-DT6} \pm \sigma_{W2-DT6}\)</span> grupo</td>
</tr>
<tr class="even">
<td>2</td>
<td>Height</td>
<td><span class="math inline">\(\mu_{W2-HT1} \pm \sigma_{W2-HT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W2-HT6} \pm \sigma_{W2-HT6}\)</span> grupo</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Leaves</td>
<td><span class="math inline">\(\mu_{W2-LT1} \pm \sigma_{W2-LT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W2-LT6} \pm \sigma_{W2-LT6}\)</span> grupo</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
<td><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td>8</td>
<td>Diameter</td>
<td><span class="math inline">\(\mu_{W8-DT1} \pm \sigma_{W8-DT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W8-DT6} \pm \sigma_{W8-DT6}\)</span> grupo</td>
</tr>
<tr class="even">
<td>8</td>
<td>Height</td>
<td><span class="math inline">\(\mu_{W8-HT1} \pm \sigma_{W8-HT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W8-HT6} \pm \sigma_{W8-HT6}\)</span> grupo</td>
</tr>
<tr class="odd">
<td>8</td>
<td>Leaves</td>
<td><span class="math inline">\(\mu_{W8-LT1} \pm \sigma_{W8-LT1}\)</span> grupo</td>
<td><span class="math inline">\(\ldots\)</span></td>
<td><span class="math inline">\(\mu_{W8-LT6} \pm \sigma_{W8-LT6}\)</span> grupo</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="exr-doe6" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 8.6</strong></span> La investigación de Adnise Samanta Christophe y Meriche Nayeder Toussaint, evaluó el valor nutricional de la fruta pan (Artocarpus altilis) y sus componentes (exocarpio, mesocarpio y endocarpio) en dos etapas de maduración para su uso en la alimentación de rumiantes. Se analizaron 45 frutas, destacando que el exocarpio. Los parámetros nutricionales fueron analizados mediante un diseño factorial <span class="math inline">\(4 \times 2\)</span>, El primer factor fue la parte o componente de la planta, cuyos niveles fueron exocarpio, mesocarpio, endocarpio y fruta entera. El segundo factor fue el grado de madurez de la planta, cuyos niveles fueron inmadura y madura. En la hoja <em>nutriconal</em> del archivo <em>nutricional_24017.xlsx</em> se encuentran los datos analizados por Meriche y Adnise. Las variables presentes en el conjunto de datos son:</p>
<ul>
<li>Madurez: grado de madurez de la planta.</li>
<li>Componente: parte de la planta.</li>
<li>Repetición: número de repetición.</li>
<li>MS: porcentaje de materia seca.</li>
<li>PC: porcentaje de proteína cruda.</li>
<li>FDN: fibra detergente neutra (%)</li>
<li>FDA: fibra detergente ácida (%)</li>
<li>MM: materia mineral (%)</li>
<li>MO: materia orgánica (%)</li>
<li>CHOs: carbohidratos totales (%)</li>
</ul>
</div>
<p>Se pide, analizar el efecto del grado de madurez y del componente junto con la interacción entre la madurez y el componente sobre las variables respuesta.</p>



<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>

</main> <!-- /main -->
<script>



/* update total correct if #webex-total_correct exists */

update_total_correct = function() {

  console.log("webex: update total_correct");



  var t = document.getElementsByClassName("webex-total_correct");

  for (var i = 0; i < t.length; i++) {

    p = t[i].parentElement;

    var correct = p.getElementsByClassName("webex-correct").length;

    var solvemes = p.getElementsByClassName("webex-solveme").length;

    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;

    var selects = p.getElementsByClassName("webex-select").length;



    t[i].innerHTML = correct + " de " + (solvemes + radiogroups + selects) + " correctas";

  }

}



/* webex-solution button toggling function */

b_func = function() {

  console.log("webex: toggle hide");



  var cl = this.parentElement.classList;

  if (cl.contains('open')) {

    cl.remove("open");

  } else {

    cl.add("open");

  }

}



/* check answers */

check_func = function() {

  console.log("webex: check answers");



  var cl = this.parentElement.classList;

  if (cl.contains('unchecked')) {

    cl.remove("unchecked");

    this.innerHTML = "Esconder Respuestas";

  } else {

    cl.add("unchecked");

    this.innerHTML = "Mostrar Respuestas";

  }

}



/* function for checking solveme answers */

solveme_func = function(e) {

  console.log("webex: check solveme");



  var real_answers = JSON.parse(this.dataset.answer);

  var my_answer = this.value;

  var cl = this.classList;

  if (cl.contains("ignorecase")) {

    my_answer = my_answer.toLowerCase();

  }

  if (cl.contains("nospaces")) {

    my_answer = my_answer.replace(/ /g, "")

  }



  if (my_answer == "") {

    cl.remove("webex-correct");

    cl.remove("webex-incorrect");

  } else if (real_answers.includes(my_answer)) {

    cl.add("webex-correct");

    cl.remove("webex-incorrect");

  } else {

    cl.add("webex-incorrect");

    cl.remove("webex-correct");

  }



  // match numeric answers within a specified tolerance

  if(this.dataset.tol > 0){

    var tol = JSON.parse(this.dataset.tol);

    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)

    if (matches.reduce((a, b) => a + b, 0) > 0) {

      cl.add("webex-correct");

    } else {

      cl.remove("webex-correct");

    }

  }



  // added regex bit

  if (cl.contains("regex")){

    answer_regex = RegExp(real_answers.join("|"))

    if (answer_regex.test(my_answer)) {

      cl.add("webex-correct");

    }

  }



  update_total_correct();

}



/* function for checking select answers */

select_func = function(e) {

  console.log("webex: check select");



  var cl = this.classList



  /* add style */

  cl.remove("webex-incorrect");

  cl.remove("webex-correct");

  if (this.value == "answer") {

    cl.add("webex-correct");

  } else if (this.value != "blank") {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



/* function for checking radiogroups answers */

radiogroups_func = function(e) {

  console.log("webex: check radiogroups");



  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');

  var cl = checked_button.parentElement.classList;

  var labels = checked_button.parentElement.parentElement.children;



  /* get rid of styles */

  for (i = 0; i < labels.length; i++) {

    labels[i].classList.remove("webex-incorrect");

    labels[i].classList.remove("webex-correct");

  }



  /* add style */

  if (checked_button.value == "answer") {

    cl.add("webex-correct");

  } else {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



window.onload = function() {

  console.log("webex onload");

  /* set up solution buttons */

  var buttons = document.getElementsByTagName("button");



  for (var i = 0; i < buttons.length; i++) {

    if (buttons[i].parentElement.classList.contains('webex-solution')) {

      buttons[i].onclick = b_func;

    }

  }



  var check_sections = document.getElementsByClassName("webex-check");

  console.log("check:", check_sections.length);

  for (var i = 0; i < check_sections.length; i++) {

    check_sections[i].classList.add("unchecked");



    let btn = document.createElement("button");

    btn.innerHTML = "Mostrar Respuestas";

    btn.classList.add("webex-check-button");

    btn.onclick = check_func;

    check_sections[i].appendChild(btn);



    let spn = document.createElement("span");

    spn.classList.add("webex-total_correct");

    check_sections[i].appendChild(spn);

  }



  /* set up webex-solveme inputs */

  var solveme = document.getElementsByClassName("webex-solveme");



  for (var i = 0; i < solveme.length; i++) {

    /* make sure input boxes don't auto-anything */

    solveme[i].setAttribute("autocomplete","off");

    solveme[i].setAttribute("autocorrect", "off");

    solveme[i].setAttribute("autocapitalize", "off");

    solveme[i].setAttribute("spellcheck", "false");

    solveme[i].value = "";



    /* adjust answer for ignorecase or nospaces */

    var cl = solveme[i].classList;

    var real_answer = solveme[i].dataset.answer;

    if (cl.contains("ignorecase")) {

      real_answer = real_answer.toLowerCase();

    }

    if (cl.contains("nospaces")) {

      real_answer = real_answer.replace(/ /g, "");

    }

    solveme[i].dataset.answer = real_answer;



    /* attach checking function */

    solveme[i].onkeyup = solveme_func;

    solveme[i].onchange = solveme_func;



    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  /* set up radiogroups */

  var radiogroups = document.getElementsByClassName("webex-radiogroup");

  for (var i = 0; i < radiogroups.length; i++) {

    radiogroups[i].onchange = radiogroups_func;

  }



  /* set up selects */

  var selects = document.getElementsByClassName("webex-select");

  for (var i = 0; i < selects.length; i++) {

    selects[i].onchange = select_func;

    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  update_total_correct();

}



</script>

<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<script type="module">
if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
window._ojs.paths.runtimeToDoc = "../..";
window._ojs.paths.runtimeToRoot = "../..";
window._ojs.paths.docToRoot = "";
window._ojs.selfContained = false;
window._ojs.runtime.interpretFromScriptTags();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-regresion.html" class="pagination-link" aria-label="Correlación y Regresión">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Correlación y Regresión</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="Referencias">
        <span class="nav-page-text">Referencias</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>